# Generated by Django 3.2.16 on 2023-01-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_amount', models.FloatField()),
                ('number_of_years', models.FloatField()),
                ('return_rate', models.FloatField()),
                ('annual_additional_contribution', models.FloatField()),
            ],
        ),
    ]
