# Generated by Django 3.2.12 on 2023-01-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loancalculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=255, verbose_name='zipcode')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
                ('county', models.CharField(max_length=255, verbose_name='county')),
                ('normalizedcounty', models.CharField(max_length=255, verbose_name='normalizedcounty')),
                ('city', models.CharField(max_length=255, verbose_name='normalizedcounty')),
                ('normalizedcity', models.CharField(max_length=255, verbose_name='normalizedcounty')),
                ('taxregionname', models.CharField(max_length=255, verbose_name='taxregionname')),
                ('normalizedtaxregionname', models.CharField(max_length=255, verbose_name='normalizedtaxregionname')),
                ('combinedrate', models.IntegerField(verbose_name='combinedrate')),
                ('staterate', models.FloatField(verbose_name='staterate')),
                ('countyrate', models.FloatField(verbose_name='countyrate')),
                ('cityrate', models.IntegerField(verbose_name='cityrate')),
                ('specialrate', models.FloatField(verbose_name='specialrate')),
                ('estimatedpopulation', models.IntegerField(verbose_name='estimatedpopulation')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(verbose_name='month')),
            ],
        ),
    ]
