# Generated by Django 3.2.12 on 2023-01-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loancalculator', '0002_statetax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statetax',
            name='month',
        ),
    ]
